version: '2'
services:
  mongo:
    image: mongo:3.4
  node_modules:
    build:
     context: .
     dockerfile: Dockerfile_nodemodules
  web:
    build: .
    ports:
     - "3000:80"
    environment:
     - MONGOLAB_URI=mongodb://nitro:nitrous@ds161039.mlab.com:61039/opcode
    links:
     - mongo
    depends_on:
     - mongo
    volumes:
     - .:/starter
     - /starter/node_modules
